version: "3"
services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        ports:
            - "8080:8080"
        volumes:
            - ./server:/usr/src/app